### ISSUE TITLE
use gitlab.projects.repository.createBranch

### ISSUE THREAD

**Issue by vvvsrx** [node-gitlab/node-gitlab#128]
When I use "gitlab.projects.repository.createBranch", it shows the error

FYI~thx.

`node_modules\gitlab\lib\Utils.js:11
      } else if (projectId.indexOf("/") !== -1) {
                          ^

TypeError: Cannot read property 'indexOf' of undefined
    at Function.Utils.parseProjectId (node_modules\gitlab\lib\Utils.js:11:27)
    at ProjectRepository.createBranch (node_modules\gitlab\lib\Models\ProjectRepository.js:96:45)
    at ProjectRepository.createBranch (node_modules\gitlab\lib\Models\ProjectRepository.js:3:59)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)`

**Comment by dave-irvine** [comment]
projectId is a required parameter to pass to `gitlab.projects.repository.createBranch`.

**Comment by vvvsrx** [comment]
my before params : { id : 1,branch_name:"11",ref:"master"}
now params { projectId : 1,branch_name:"11",ref:"master"}
it's run~
thank you very much.
