### ISSUE TITLE
CLI seems to be broken

### ISSUE THREAD

**Issue by osher** [node-gitlab/node-gitlab#491]
**Description**

Using CLI ends with rough errors

I'm trying to follow the getting started from the readme.
I succeeded using the package in node shell, pulled a project, updated project - fun.
I'm trying the CLI - but I get pretty rough errors.

```
module.js:550
    throw err;
    ^
Error: Cannot find module '../../dist/map.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/gitlab-setup/node_modules/gitlab/dist/cli.js:2:88616)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Steps to reproduce**
```
$ npm ls gitlab
tm-gitlab-setup@1.0.0 /home/user/gitlab-setup
`-- gitlab@11.4.2 
$ export GITLAB_TOKEN=...shhh!!
$ gitlab prjects show --projectId 15303334
```
And you get the output above.
I'm now using some ubuntu.

**Expected behaviour**
I donno, I'm trying to see how it behaves... I'd expect some YAML/JSON output or something.. :)

**Actual behaviour**
The error above

**Possible fixes**
I tried to hack in the minified `cli.js`  the `require('../../dist/map.json')` to `require('../dist/map.json')`, but then it fails with 
```
SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Here I had to stop and get back to my original assignment...

**Comment by jdalrymple** [comment]
Well thats frustrating. Sorry about that :(. Gonna have some free time this weekend to clean up the buggy issues. Ill get to this ASAP :D

**Comment by osher** [comment]
thanks for letting me know, and thanks for your efforts :) :+1:

**Comment by osher** [comment]
Thanks for your efforts!
I'll get back to this task somewhere next week, and continue from where I left :)
